# Generated by Django 6.1.1 on 2026-09-24 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_farmer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('irrigation_type', models.CharField(max_length=50)),
                ('crop_stage', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farmers.farm')),
            ],
        ),
    ]
